# Generated by Django 5.0.4 on 2024-05-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_image_category_thrumbnail_product_asdsasd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Иконка',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='thrumbnail',
            new_name='Картинка',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Категория',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Название',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='Ссылка',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Цена',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='asdsasd',
            new_name='Является ли рекомендуемым',
        ),
    ]
