# Generated by Django 5.0.4 on 2024-05-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_options_rename_name_category_название'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Иконка',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Название',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Ссылка',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Картинка',
            new_name='thrumbnail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Категория',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Иконка',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Является ли рекомендуемым',
            new_name='is_best',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Название',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Цена',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Ссылка',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Картинка',
            new_name='thrumbnail',
        ),
    ]
