# Generated by Django 5.0.4 on 2024-05-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_client_name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telegram_ID', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(blank=True, to='product.product')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
